on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
name: Release
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cashapp/activate-hermit@v1
        with:
          cache: true
      - id: build
        shell: bash
        run: |
          cargo build --release
          export TARGET_PATH=target/release/mktg-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
          mv target/release/mktg ${TARGET_PATH}
          bzip2 -f9 ${TARGET_PATH}
          echo "TARGET_PATH=${TARGET_PATH}.bz2" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.TARGET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "mktg-*.bz2"
