on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
name: Release x86_64-unknown-linux-gnu
jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cashapp/activate-hermit@v1
        with:
          cache: true
      - id: build
        shell: bash
        run: |
          rustup install stable
          cargo build --release --target x86_64-unknown-linux-gnu
          export TARGET_PATH=target/release/mktg-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
          mv target/release/mktg ${TARGET_PATH}
          bzip2 -f9 ${TARGET_PATH}
          echo "TARGET_PATH=${TARGET_PATH}.bz2" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: mktg-linux-x86_64
          path: ${{ steps.build.outputs.TARGET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-macos:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@v2
      - uses: cashapp/activate-hermit@v1
        with:
          cache: true
      - id: build
        shell: bash
        run: |
          rustup install stable
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}
          export TARGET_PATH=target/${{ matrix.target }}/release/mktg
          mv target/${{ matrix.target }}/release/mktg ${TARGET_PATH}
          bzip2 -f9 ${TARGET_PATH}
          echo "TARGET_PATH=${TARGET_PATH}.bz2" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: mktg-${{ matrix.target }}
          path: ${{ steps.build.outputs.TARGET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "mktg-*.bz2"
